refactor: missing function, query method
kodiiing/core pull request #19
Opened 2023-11-02 23:14 UTC by YogiPristiawan

## 📑 Deskripsi
Menyesuaikan missing function dan query pada modul auth

## ✅ Checks
- [v ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [v] All the tests have passed

## ℹ Informasi Tambahan

2023-11-04 05:23 UTC, WahidinAji commented
walahhh, tiwas aku ubah wkwkwk. yowes gpp. lanjutin aja. btw, querynya dipindah ke goose ya.

terus, jangan lupa gabit tinyint ke smallint. karena pgsql ga ada tinyint. gatau ini bapack @aldy505 kok bisa tinyint ;D

2023-11-04 05:27 UTC, YogiPristiawan commented
> walahhh, tiwas aku ubah wkwkwk. yowes gpp. lanjutin aja. btw, querynya dipindah ke goose ya.
> 
> terus, jangan lupa gabit tinyint ke smallint. karena pgsql ga ada tinyint. gatau ini bapack @aldy505 kok bisa tinyint ;D

apanya yg kamu ubah Ji? kayaknya aku ga ngubah-ngubah file migration

2023-11-04 05:39 UTC, WahidinAji requested changes

2023-11-04 05:39 UTC, WahidinAji commented on auth/service/user.go
> +	var insertId int64
ini hapus aja,

2023-11-04 05:39 UTC, WahidinAji commented on auth/service/user.go
> +			RETURNING
```suggestion
			RETURNING id
```

2023-11-04 05:39 UTC, WahidinAji commented on auth/service/user.go
> +	).Scan(&insertId)
```suggestion
	).Scan(&id)
```

ini pake named return, bisa manfaatin itu

2023-11-04 05:39 UTC, WahidinAji commented on auth/service/user.go
> +	tx, err := d.pool.Begin(ctx)
beginTx, kasih IsoLevel. pake ReadCommitted, tambahin `AccessMode: pgx.ReadOnly`
```suggestion
	tx, err := d.pool.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.ReadCommitted, AccessMode: pgx.ReadWrite})
```

2023-11-04 05:41 UTC, WahidinAji commented on auth/service/repository.go
> +		_, err := tx.Exec(
di pgx juga ada prepare btw pack,
see https://github.com/jackc/pgx/blob/4ebf1d2e0baa87ab6afbbf6a0947c9fb8a30e9d4/conn_test.go#L384

2023-11-04 05:43 UTC, YogiPristiawan commented on auth/service/user.go
> +	tx, err := d.pool.Begin(ctx)
`ReadWrite` maksudnya?

2023-11-04 05:45 UTC, WahidinAji commented on auth/service/user.go
> +	tx, err := d.pool.Begin(ctx)
iya

2023-11-04 05:49 UTC, YogiPristiawan commented on auth/service/repository.go
> +		_, err := tx.Exec(
oh ok. btw kenapa harus pakai prepare?

2023-11-04 09:17 UTC, WahidinAji commented on auth/service/repository.go
> +		_, err := tx.Exec(
if there're 5 data
with prepare
```sql
prepare anu insert bla,bla,bla

for i range data
  exec.anu(i.bla,i.bla2,i.bla3)

without prepare
for i range data
   inser bla1,bla2,bla3
```

lebih sederhaanya

```sql
bapak lebih pilih 
insert into table(bla,bla,bla)
insert into table(bla,bla,bla)
insert into table(bla,bla,bla)
insert into table(bla,bla,bla)
insert into table(bla,bla,bla)

atau
inser into table(
(bla,bla2,bla3),
(bla,bla2,bla3),
(bla,bla2,bla3),
(bla,bla2,bla3),
(bla,bla2,bla3),
);
```
terus, kalau penasaran lagi kenapa.

coba bapak benchmark di yugabytenya langsung,
if insert with/without prepare.

2023-11-08 12:09 UTC, YogiPristiawan commented
done at [410399843dc1](https://github.com/kodiiing/core/pull/19/commits/e60bbed273937567e4f33b9a97e434b019081ea1) check lagi ya ji

2023-11-10 10:05 UTC, WahidinAji commented
> walahhh, tiwas aku ubah wkwkwk. yowes gpp. lanjutin aja. btw, querynya dipindah ke goose ya.
> 
> terus, jangan lupa gabit tinyint ke smallint. karena pgsql ga ada tinyint. gatau ini bapack @aldy505 kok bisa tinyint ;D

migrationnya pack

2023-11-10 13:45 UTC, aldy505 approved these changes

2023-11-10 14:07 UTC, YogiPristiawan commented
i changed `timestamp` into `timestamptz` at https://github.com/kodiiing/core/pull/19/commits/7f6eb59ed4d05fc8412fc3fa173dc874a5201e5d and https://github.com/kodiiing/core/pull/19/commits/22667ec703b190a48922f0470082e70024f1d72d

@aldy505

2023-11-14 11:15 UTC, WahidinAji approved these changes
GBTM

2023-11-14 11:16 UTC, merged