migrate: create task_schema
kodiiing/core pull request #27
Opened 2023-12-03 07:45 UTC by YogiPristiawan

Please enter the commit message for your changes. Lines starting

Closes # 

## 📑 Deskripsi

## ✅ Checks

- [v] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [v] All the tests have passed

## ℹ Informasi Tambahan

2023-12-03 09:59 UTC, aldy505 requested changes

2023-12-03 09:59 UTC, aldy505 commented on migrations/00004_create_task_schema.sql
> +    author VARCHAR(63) NOT NULL,
`author` should refer to the user's ID, instead of their name, so it should be `BIGINT`

2023-12-03 09:59 UTC, aldy505 commented on migrations/00004_create_task_schema.sql
> +    finished_at TIMESTAMPTZ NULL,
These shouldn't be null

2023-12-03 10:37 UTC, yogip07 commented on migrations/00004_create_task_schema.sql
> +    finished_at TIMESTAMPTZ NULL,
`finished_at` gaboleh null? gimana kalau task nya masih in progress. misal masih dengan `status = 1`

2023-12-06 14:17 UTC, aldy505 requested changes

2023-12-06 14:17 UTC, aldy505 commented on main.go
> +		log.Printf("listeing on port: %s", config.Port)
```suggestion
		log.Printf("Listening on port: %s", config.Port)
```

Sebenernya kalo ini pake zerolog, lebih baik jadi:
```go
log.Info().Msgf("Listening on %s", net.JoinHostPort(config.Host, config.Port))
```

2023-12-06 14:17 UTC, aldy505 commented on task/repository/list_task.go
> +	return
Transaction nggak pernah di commit?

2023-12-06 14:36 UTC, YogiPristiawan commented on task/repository/list_task.go
> +	return
eh iya maap

2023-12-06 14:36 UTC, YogiPristiawan commented on migrations/00004_create_task_schema.sql
> +    finished_at TIMESTAMPTZ NULL,
ini gmn? @aldy505

2023-12-07 04:34 UTC, yogip07 commented on task/repository/list_task.go
> +	return
Done at `48f591d`

2023-12-09 01:06 UTC, aldy505 commented on migrations/00004_create_task_schema.sql
> +    finished_at TIMESTAMPTZ NULL,
`started_at` yang nggak boleh null

2023-12-09 03:35 UTC, YogiPristiawan commented on migrations/00004_create_task_schema.sql
> +    finished_at TIMESTAMPTZ NULL,
done 3140f4e

2023-12-09 09:43 UTC, aldy505 approved these changes

2023-12-09 09:44 UTC, merged

2023-12-09 10:05 UTC, YogiPristiawan commented
thanks