feat: post assessment
kodiiing/core pull request #33
Opened 2023-12-30 11:00 UTC by YogiPristiawan

Closes # 

## 📑 Deskripsi

## ✅ Checks

- [v] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Informasi Tambahan

2023-12-30 11:54 UTC, aldy505 requested changes

2023-12-30 11:54 UTC, aldy505 commented on migrations/00004_create_task_schema.sql
> +    comments VARCHAR(511) NOT NULL DEFAULT ''
Jangan gini, bikin migration file baru. Liat https://github.com/pressly/goose?tab=readme-ov-file#create

```sh
cd migrations
goose create user_tasks_comments sql
```

yang line ini di delete aja, di `user_tasks_comments` nanti tinggal `ALTER TABLE ADD COLUMN`

2023-12-30 11:54 UTC, aldy505 commented on task/repository/count_user_task_by_task_id.go
> +}
Nggak mau ambil connection dari pool dulu?

2023-12-30 11:54 UTC, aldy505 commented on task/repository/insert_task_assessment.go
> +		return 0, pgx.ErrNoRows
Jangan return error nya `pgx`, bikin error kita sendiri aja

2023-12-30 11:54 UTC, aldy505 commented on task/service/post_task_assessment.go
> +	taskId, _ := strconv.ParseInt(req.TaskId, 10, 64)
error nya ini jangan di ignore.

2023-12-30 11:54 UTC, aldy505 commented on task/service/post_task_assessment.go
> +				StatusCode: http.StatusNotFound,
BadRequest aja

2023-12-30 11:54 UTC, aldy505 commented on task/service/post_task_assessment.go
> +		}
Ini nggak usah return error, cuma butuh log somewhere.

2023-12-31 05:16 UTC, YogiPristiawan commented on migrations/00004_create_task_schema.sql
> +    comments VARCHAR(511) NOT NULL DEFAULT ''
oh kirain gaperlu nambah, salnya table nya belum dimigrasi

2023-12-31 05:17 UTC, YogiPristiawan commented on task/service/post_task_assessment.go
> +	taskId, _ := strconv.ParseInt(req.TaskId, 10, 64)
tetep harus dihandle? meskipun di level validation udah dihandle

2023-12-31 05:22 UTC, YogiPristiawan commented on task/repository/count_user_task_by_task_id.go
> +}
Bukannya udah dihandle dari pgx nya?
https://github.com/jackc/pgx/blob/6f2ce92356f35263258ef7baa4cde86a3e1c6255/pgxpool/pool.go#L617-L637

2023-12-31 07:22 UTC, YogiPristiawan commented on task/service/post_task_assessment.go
> +		}
masukin ke log aja?

2023-12-31 08:54 UTC, aldy505 commented on task/repository/count_user_task_by_task_id.go
> +}
Oh yasudah

2023-12-31 08:55 UTC, YogiPristiawan commented on task/repository/count_user_task_by_task_id.go
> +}
ok

2023-12-31 08:56 UTC, aldy505 requested changes

2023-12-31 08:56 UTC, aldy505 commented on task/repository/insert_task_assessment.go
> +		return 0, task_stub.TaskRepositoryErrNoRows
jangan ngubah apapun di stub, stub kan di generate sama [proto2http](https://github.com/kodiiing/proto2http), error nya kalo di level repository ya jadi milik repository

2023-12-31 08:56 UTC, aldy505 commented on task/repository/insert_task_assessment.go
> +			return 0, task_stub.TaskRepositoryErrNoRows
ini juga sama

2023-12-31 08:58 UTC, YogiPristiawan commented on task/repository/insert_task_assessment.go
> +		return 0, task_stub.TaskRepositoryErrNoRows
oh jadi di taruh di repository aja?

2023-12-31 09:26 UTC, aldy505 approved these changes

2023-12-31 09:27 UTC, merged