add the master version of Typesense image ^0.24.0.rcn17.
kodiiing/core pull request #4
Opened 2022-10-18 15:11 UTC by WahidinAji

why is this one is happening? because the current stable version doesn't support the nested field. it'll be supported at least on the 0.24 version

2022-10-19 23:33 UTC, aldy505 requested changes
dockerfile khusus typesensenya yang harusnya dapet version bump, bukan docker composenya

2022-10-20 09:28 UTC, WahidinAji commented
> t version bump, bukan docker composenya

ohh buat dockerfile khusus untuk typesensenya?

2022-10-20 09:34 UTC, WahidinAji commented
> dockerfile khusus typesensenya yang harusnya dapet version bump, bukan docker composenya

oalahhh gue kala liat ada ini 
![image](https://user-images.githubusercontent.com/48281037/196912807-63b3280c-2124-4d2a-98b6-6d816e49c166.png)

2022-10-23 04:06 UTC, aldy505 approved these changes

2022-10-23 04:06 UTC, merged